language: java
jdk:
  - openjdk8
sudo: false # faster builds

install: true

cache:
  directories:
    - "$HOME/.m2"

script: "mvn clean test cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "build failed!"